### ISSUE TITLE
Can't install library with NPM

### ISSUE THREAD

**Issue by mhosman** [zerohouse/router-tab#1]
```
npm ERR! code E404
npm ERR! 404 Not Found: @zerohouse/route-tab@latest
```

**Comment by zerohouse** [comment]
@mhosman 

sorry; miss spelled;;;

npm install @zerohouse/router-tab --save

**Comment by mhosman** [comment]
Yeah, I just created a pull request with that little change 👍

**Comment by mhosman** [comment]
#2

**Comment by zerohouse** [comment]
@mhosman thank you I am not good at englishTT
