### ISSUE TITLE
Angular 7 compatibility

### ISSUE THREAD

**Issue by ThePatzen** [zerohouse/router-tab#6]
V 0.0.5

I get the following messages:
`npm WARN @zerohouse/router-tab@0.0.5 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @zerohouse/router-tab@0.0.5 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @zerohouse/router-tab@0.0.5 requires a peer of @angular/cdk@^6.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN @zerohouse/router-tab@0.0.5 requires a peer of @angular/material@^6.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN @zerohouse/router-tab@0.0.5 requires a peer of @angular/router@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.`

Seems it works fine with 7.x!

Could you update dependencies?^^

Best Regards!

**Comment by zerohouse** [comment]
0.0.7 it fixed

**Comment by ThePatzen** [comment]
Thank you very much!!
